server:
  port: 3000

db:
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  database: 'emakina'
  synchronize: true

jwt:
  secret: 'topSecret51'

auth:
  google_client_id: '104417906133543098950'
